### ISSUE TITLE
A CLI that generates a library supporting the new and old architecture

### ISSUE THREAD

**Issue by a7medev** [cipolleschi/RNNewArchitectureLibraries#1]
This repo is a very great reference for building a new library that supports the new and old architecture at once and it would be really great if we had a CLI that generates the library automatically kinda like `create-react-native-library` and `create-react-native-module` or better yet have it in one of those already existing CLIs.

**Comment by cortinico** [comment]
Thanks for raising this point.

I suggest you open an issue on those two repos, linking this repo. I believe they could update their templates using this repo as a reference.

Closing as there is nothing actionable on this for us.
