### ISSUE TITLE
Would be useful to have a kotlin example for both Turbo and Fabric module

### ISSUE THREAD

**Issue by zabojad** [cipolleschi/RNNewArchitectureLibraries#13]
I can't find any...

**Comment by cortinico** [comment]
The whole documentation on the website is updated to have both Kotlin & Java examples:
https://reactnative.dev/docs/0.71/the-new-architecture/pillars-turbomodules

**Comment by zabojad** [comment]
@cortinico there are things missing in the doc like how to send events from components and modules with the new architecture...

**Comment by cortinico** [comment]
Yup but those are missing on both languages right? Also please join the New Architecture Working Group if you have this and other type of feedback: https://github.com/reactwg/react-native-new-architecture
