### ISSUE TITLE
[question] what is the purpose of `ViewManagerDelegate`

### ISSUE THREAD

**Issue by vonovak** [cipolleschi/RNNewArchitectureLibraries#14]
When migrating a component to Fabric, there is a step documented here https://reactnative.dev/docs/next/the-new-architecture/pillars-fabric-components#centeredtextmanagerjava which adds the following

```
    private final ViewManagerDelegate<CenteredText> mDelegate;

    public CenteredTextManager(ReactApplicationContext context) {
        mDelegate = new RTNCenteredTextManagerDelegate<>(this);
    }

    @Nullable
    @Override
    protected ViewManagerDelegate<CenteredText> getDelegate() {
        return mDelegate;
    }
```

I'd like to know what the purpose of the delegate is. Is it mandatory? Implementing the `RTNCenteredTextManagerInterface` does not enforce the presence of  `getDelegate()` and I'm wondering what it's purpose is, because all the delegate does is that is ends up calling the methods on the `ViewManager`. Is it for imperative command dispatching?

I implemented a Fabric component without `getDelegate()` and it appears to work properly.

Thank you for the answer :)

**Comment by cortinico** [comment]
Hi @vonovak 
Can I ask you to ask again over here:
https://github.com/reactwg/react-native-new-architecture

We're trying to keep all the Q&A for New Architecture in the same place.
Please link your post here, and I'm happy to answer over there
